title: Déleon Blog
description: "Blog de Informática y Ciberseguridad"
author:
  name: "Déleon"
  email: ""
  url: "https://github.com/LawlietJH"

source: .
destination: ./_site/
permalink: /:categories/:title
paginate: 7
paginate_path: /page/:num/
google_analytics: "UA-235220550-1"
timezone: America/Mexico_City

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap


# Custom variables
owner: "Déleon"
year: "2022"
debug: false
