title: Déleon Blog
description: "Blog de Informática y Ciberseguridad"
author:
  name: "Deleon"
  email: ""
  url: "https://github.com/LawlietJH"

baseurl: /

source: .
destination: ./_site/
permalink: /:categories/:title
paginate: 7
paginate_path: /page/:num/
google_analytics: ${{ secrets.ANALYTICS_ID }}

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner: "Déleon"
year: "2022"
debug: false
